#!/usr/bin/env bash
#
# RaidTheRoot (RTR) - environment teardown / cleanup
# Member 1 (Platform & Architecture)
#
# Removes the RUNNING environment and GENERATED files only:
#   - the RTR Docker containers, networks, volumes and built images
#   - the self-signed TLS certificate (regenerated by deploy.sh)
#   - Python caches and test scratch output
#
# It NEVER touches your source: no stage folders, no scripts, no .env,
# no .env.template, no README, no docker-compose.yml, no Dockerfiles,
# no generated challenge artefacts that are committed (the .png/.enc/.pcap),
# and no git history. Running deploy.sh afterwards brings everything back.
#
# Usage:
#   ./scripts/teardown.sh           # DRY RUN - shows what would be removed
#   ./scripts/teardown.sh --yes     # actually remove
#
# Safe to run from anywhere; it resolves the repo root itself.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

APPLY=0
[[ "${1:-}" == "--yes" || "${1:-}" == "-y" ]] && APPLY=1

say()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
item() { printf '    %s\n' "$*"; }
ok()   { printf '    \033[0;32m[ok]\033[0m %s\n' "$*"; }
warn() { printf '    \033[0;33m[!]\033[0m %s\n' "$*"; }

run() {
    if [[ "$APPLY" -eq 1 ]]; then
        eval "$@" 2>/dev/null || true
    else
        printf '    would run: %s\n' "$*"
    fi
}

if [[ "$APPLY" -eq 0 ]]; then
    printf '\n\033[1;33m*** DRY RUN ***\033[0m  nothing will be removed.\n'
    printf 'Re-run with  --yes  to apply.\n'
fi

# --- 1. compose stacks down (containers + their networks/volumes) -----
say "Docker Compose stacks"
run "docker compose -f stage3-webportal/docker-compose.yml down -v --rmi local"
run "docker compose -f stage6-bankcore/docker-compose.yml down -v --rmi local"
run "docker compose down -v --rmi local"
ok "control plane + challenge stacks"

# --- 2. any RTR containers left over ----------------------------------
say "Stray RTR containers"
for c in rtr-ctfd rtr-db rtr-cache rtr-proxy rtr-stage3 rtr-stage6; do
    if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "$c"; then
        item "removing container $c"
        run "docker rm -f $c"
    fi
done

# --- 3. RTR networks --------------------------------------------------
say "RTR networks"
for n in rtr-control stage3-net stage6-net; do
    if docker network ls --format '{{.Name}}' 2>/dev/null | grep -qx "$n"; then
        item "removing network $n"
        run "docker network rm $n"
    fi
done

# --- 4. RTR-built images ----------------------------------------------
say "RTR-built images"
imgs="$(docker images --format '{{.Repository}}:{{.Tag}}' 2>/dev/null \
        | grep -E 'raidtheroot|rtr-stage' || true)"
if [[ -n "$imgs" ]]; then
    echo "$imgs" | while read -r img; do
        item "removing image $img"
        run "docker rmi -f $img"
    done
else
    item "none"
fi

# --- 5. generated (non-source) files ----------------------------------
# Only files that deploy.sh / generate scripts recreate. Nothing authored.
say "Generated local files"

if [[ -d nginx/certs ]]; then
    item "TLS certificate (nginx/certs/) - regenerated by deploy.sh"
    run "rm -f nginx/certs/rtr.crt nginx/certs/rtr.key"
fi

item "Python caches (__pycache__, *.pyc)"
run "find . -path ./.git -prune -o -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null"
run "find . -path ./.git -prune -o -name '*.pyc' -type f -delete"

if [[ -d tests/output ]]; then
    item "test scratch output (tests/output/*)"
    run "find tests/output -type f ! -name '.gitkeep' -delete"
fi

# --- what is explicitly PRESERVED -------------------------------------
say "Preserved (never touched)"
item "all source: stage folders, scripts/, nginx/nginx.conf, app code"
item ".env, .env.template, README.md, docker-compose.yml, Dockerfiles"
item "committed artefacts: *.png, *.enc, *.pcap (regenerable, but kept)"
item "ctfd-config/rtr-event-export.zip"
item ".git history"

# --- done -------------------------------------------------------------
if [[ "$APPLY" -eq 1 ]]; then
    say "Cleanup complete"
    item "run ./scripts/deploy.sh to bring the box back up"
else
    say "Dry run complete - re-run with --yes to apply"
fi
